services:
  # A background worker that runs the Telegram bot
  - type: worker
    name: telegram-roadmap-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: SERVICE_ACCOUNT_PATH
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
